# Generated by Django 6.0.4 on 2026-05-02 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unique', models.CharField(max_length=100, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('identifiant_verification', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('ANNULEE', 'Annulée'), ('EXPIREE', 'Expirée')], default='VALIDE', max_length=20)),
                ('date_expiration', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('raison_archivage', models.TextField(blank=True, null=True)),
                ('attestation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='attestations.attestation')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_TRAITEMENT', 'En traitement'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='accounts.profildemandeur')),
                ('type_attestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='attestations.typeattestation')),
            ],
        ),
        migrations.AddField(
            model_name='attestation',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='attestations.demandeattestation'),
        ),
        migrations.CreateModel(
            name='FichierPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=150)),
                ('chemin_fichier', models.FileField(upload_to='attestations/pdf/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('attestation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fichier_pdf', to='attestations.attestation')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('GENERATION', 'Génération'), ('TELECHARGEMENT', 'Téléchargement'), ('VERIFICATION', 'Vérification'), ('ANNULATION', 'Annulation'), ('ARCHIVAGE', 'Archivage')], max_length=30)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('objet_concerne', models.CharField(blank=True, max_length=100, null=True)),
                ('detail_contextuel', models.TextField(blank=True, null=True)),
                ('attestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux', to='attestations.attestation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_verification', models.URLField(max_length=255)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('attestation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='attestations.attestation')),
            ],
        ),
        migrations.CreateModel(
            name='ModeleAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_attestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='attestations.typeattestation')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resultat', models.CharField(choices=[('VALIDE', 'Valide'), ('ANNULEE', 'Annulée'), ('EXPIREE', 'Expirée'), ('INTROUVABLE', 'Introuvable')], max_length=20)),
                ('attestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='attestations.attestation')),
            ],
        ),
    ]
